[features]
seeds = false
[programs.localnet]
solana_twitter = "9pCHeTL6CVzUsWgNbZn52wvvNz46RmhvgLezpjtniGpM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/mort1b/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
